spring:
  application:
    name: auth-api
    datasource:
      url: jdbc:postgresql://localhost:5432/kn-db
      username: root
      password: root
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
jwt:
  secret: secret
